Nexus registry secret for pub and delivery clusters
Financial-Times/k8s-aws-delivery-poc pull request #152
Opened 2017-09-21 11:21 UTC by JermilaPaulDhas

2017-09-21 11:23 UTC, sbuliarca approved these changes

2017-09-27 13:03 UTC, tamas-molnar requested changes
@JermilaPaulDhas  please fix filename typo: `nexus-regisrty-secret-template.yaml`

2017-09-27 15:58 UTC, JermilaPaulDhas commented
@tamas-molnar file name has been fixed

2017-09-28 06:07 UTC, tamas-molnar approved these changes

2017-09-28 06:08 UTC, merged