Add list notifications rw
Financial-Times/k8s-aws-delivery-poc pull request #3
Opened 2017-01-19 07:58 UTC by MihaiSorinMoisa

2017-01-19 08:33 UTC, davidbalazs93 requested changes

2017-01-19 08:33 UTC, davidbalazs93 commented on kube-config-files/list-notifications-rw-service.yaml
> +              value: "10"
as a general question here, should we use config items for such values?
https://kubernetes.io/docs/user-guide/configmap/

2017-01-19 09:35 UTC, sbuliarca commented on kube-config-files/list-notifications-rw-service.yaml
> +              value: "10"
We should demonstrate that it is possible to be done with config maps, and after that we should just hardcode it and put a comment that it should be moved to config maps.

2017-01-23 13:58 UTC, davidbalazs93 approved these changes

2017-01-23 13:58 UTC, sbuliarca approved these changes

2017-01-23 14:05 UTC, merged